apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: course-api
  name: course-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: course-api
    spec:
      containers:
        - image: northamerica-south1-docker.pkg.dev/microservicios-udemy-454719/image-registry/courses-api:v1.0.0
          name: courses-api
          env:
          - name: PORT
            value: "3000"
          - name: DATABASE_URL
            value: "postgresql://neondb_owner:npg_m3ScKkyCq8Ti@ep-red-bar-a52m21d5-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
          - name: JWT_SECRET
            value: "jsonwebtokensecretQ"
          resources: {}
status: {}
