apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: course-api
  name: course-api
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: course-api
  type: NodePort
status:
  loadBalancer: {}
