apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: course-api
  name: course-api
spec:
  ports:
    - name: http
      port: 80 # Puerto expuesto para el Ingress o tráfico externo
      targetPort: 3000 # El puerto en el contenedor donde tu app escucha
      protocol: TCP
  selector:
    app: course-api
  type: NodePort
status:
  loadBalancer: {}
