name: Build and Push to GCP Artifact Registry

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: courses-api
          service_account_key: ${{ secrets.GCP_KEY_JSON }}

      - name: Set up Docker auth for GCP
        run: |
          echo '${{ secrets.GCP_KEY_JSON }}' > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker northamerica-south1-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          #file: ./dockerfile.prod
          push: true
          tags: northamerica-south1-docker.pkg.dev/microservicios-udemy-454719/image-registry/courses-api:v1.0.0
